### ISSUE TITLE
"W10: Warning: Changing a readonly file" when using `view` (vim in readonly mode)

### ISSUE THREAD

**Issue by blueyed** [tomtom/tlib_vim#18]
When using `view` (which starts vim in readonly mode), calling `:TRecentlyUsedFiles` triggers this error in tlib:

```
Error detected while processing function tmru#SelectMRU..tlib#input#ListW..539:
line   33:
W10: Warning: Changing a readonly file
```

Function #539 is:

```
function! s:prototype.DisplayList(...) dict "{{{3
```

The code ([source](https://github.com/tomtom/tlib_vim/blob/master/autoload/tlib/World.vim#L1132)):

```
call append(0, lines)
```

The calls to `tlib#normal#WithRegister('gg"tdG', 't')` and `tlib#normal#WithRegister('G"tddgg', 't')` fail silently (through try/finally).

It appears that the tlib/tmru should explicitly set `noreadonly` for its buffer maybe?!

**Comment by Marezbadei** [comment]
W10: Warning: Changing a readonly file
