### ISSUE TITLE
Initialization Error on Windows

### ISSUE THREAD

**Issue by mark13hardware** [tomtom/tlib_vim#19]
Upon launching Windows gvim, an error dialog pops up complaining about being unable to redefine function tlib#sys#IsExecutable in vimfiles\autoload\tlib\sys.vim on line 34.

I troubleshot as best I could by deleting my vimfiles directory, then re-installed only tlib and tsekeleton.  I used the latest vimballs from vim.org.  I still get the same error when launching gvim.

I am using Windows 7 64-bit, and the 32-bit gvim installed with the MS-Windows self-installing executable, gvim74.exe, from http://www.vim.org/download.php

The entirety of the error message is copy/pasted below:
Error detected while processing C:\Users\mark13\
vimfiles\autoload\tlib\sys.vim:line   34:E127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useE127: Cannot redefine function tlib#sys#IsExecuta
ble: It is in useline   40:E132: Function call depth is higher than 
'maxfuncdepth'Error detected while processing function 
tlib#sys#IsExecutable:line    8:E132: Function call depth is higher than 
'maxfuncdepth'Error detected while processing function 
tlib#sys#IsExecutable..tlib#sys#IsCygwinBin:line    7:E132: Function call depth is higher than 
'maxfuncdepth'E132: Function call depth is higher than 
'maxfuncdepth'

**Comment by tomtom** [comment]
> I troubleshot as best I could by deleting my vimfiles directory, then 
> re-installed only tlib and tsekeleton. I used the latest vimballs from 
> vim.org. I still get the same error when launching gvim. 
Could you please try the version from github and check if the problem 
persists. Thanks.
