### ISSUE TITLE
TLibTrace duplicate help-file tag

### ISSUE THREAD

**Issue by Garonenur** [tomtom/tlib_vim#22]
after updating with VAM i get an error that TLibTrace has duplicate tags within tlib.txt

**Comment by gisphm** [comment]
+1 @tomtom

**Comment by tomtom** [comment]
Should be fixed with the latest commit.

**Comment by Garonenur** [comment]
yes, it is, thank you!

**Comment by gisphm** [comment]
After updating plugins using `neobundle.vim` on my virtual machine today, it comes out the error message again.
```
[neobundle] Vim(helptags):E154: Duplicate tag ":TLibTrace" in file /home/vagrant/.vim/bundle/.neobundle/doc/tlib.txt
```
@tomtom Please fix it.
