### ISSUE TITLE
line 77: E1208: -complete used without allowing arguments in vim 8.2.3570

### ISSUE THREAD

**Issue by zuloloxi** [tomtom/tlib_vim#35]
Hello,
To solve the error :
line 77: E1208: -complete used without allowing arguments in https://github.com/tomtom/tlib_vim/commit/70c4e222464020edc2809c932b488daaf891eeef
I modified the line 77 like : 
command! -nargs=? -complete=command TBrowseScriptnames call tlib#cmd#TBrowseScriptnames()
and tested here : 
https://github.com/zuloloxi/vim/commit/32ddf8095b78c51ee6d8663f747f5e6f907ff8ef

**Comment by tomtom** [comment]
Please update the plugin. See the related issues.
