### ISSUE TITLE
Error with 02tlib.vim

### ISSUE THREAD

**Issue by grav3m1nd-byte** [tomtom/tlib_vim#36]
When using this vim plugin, and after the latest update, its use throws this error as in line 77, the command was set not to allow arguments when it seems like it needs at least one.

```shell
Error detected while processing ./tlib/plugin/02tlib.vim:
line   77: E1208: -complete used without allowing argumentsPress ENTER or type command to continue
```

**Comment by grav3m1nd-byte** [comment]
This error should be resolved by using the following on line 77 (`-nargs=1`):

```shell
command! -nargs=1 -complete=command TBrowseScriptnames call tlib#cmd#TBrowseScriptnames()
```

**Comment by tomtom** [comment]
Please try the current version from github. Thanks.
